/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Apache.Hadoop.Hive
{
  public enum AdjacencyType
  {
    CONJUNCTIVE = 0,
    DISJUNCTIVE = 1,
  }
}
