/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Apache.Hadoop.Hive
{
  public enum NodeType
  {
    OPERATOR = 0,
    STAGE = 1,
  }
}
