/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Apache.Hadoop.Hive
{
  public enum PrincipalType
  {
    USER = 1,
    ROLE = 2,
    GROUP = 3,
  }
}
