/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Apache.Hadoop.Hive
{
  public enum TaskType
  {
    MAP = 0,
    REDUCE = 1,
    OTHER = 2,
  }
}
